I`ve added group support for distribution students into them
thesanderchat/SpringDemoGradle pull request #1
Opened 2022-05-16 09:52 UTC by thesanderchat

2022-05-17 17:27 UTC, aquariusmaster requested changes

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/Group.java
> +    @Column(nullable = false)
Primary key cannot be null

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +    @Autowired
You can remove it

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +    public GroupController(GroupService groupService) {
Replace by lombok

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +    private GroupDto getGroups(@PathVariable("groupId") Long groupId) {
wrong access level

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +    private List<GroupDto> getGroups() {
Wrong access level

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    @Column(nullable = false)
What is the purpose of @Column here?

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    @Column(nullable = false)
Why you use Column here?

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    public GroupDto(@NonNull String name, @NonNull LocalDate dateOfCreation, List<Student> studentList) {
Use builder instead of these constructors

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupService.java
> +    public GroupService(GroupRepository groupRepository, GroupMapper groupMapper) {
Use lombok

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/Student.java
> +    @JsonBackReference
Why you need it here?

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/Student.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
Why you need cascade type all here?

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/Student.java
> +    @PrimaryKeyJoinColumn(name = "groups_id")
Interesting, never saw this annotation before

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/Student.java
>      private Integer age;
I think you can remove that, bc you don't use it

2022-05-17 17:27 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/StudentService.java
> +    public StudentService(StudentRepository studentRepository, StudentMapper studentMapper, GroupRepository groupRepository) {
Use lombok

2022-05-17 19:20 UTC, aquariusmaster requested changes

2022-05-17 19:20 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    private List<Student> studentList;
There must be StudentDto not Student

2022-05-17 19:20 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    @Column(nullable = false)
don't need that

2022-05-17 19:20 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +}
add new line

2022-05-17 19:20 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupService.java
> +}
add empty line

2022-05-17 19:20 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/Student.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
this is wrong to manage a group through student

2022-05-17 19:25 UTC, thesanderchat commented on src/main/java/com/example/demo/group/Group.java
> +    @Column(nullable = false)
fixed

2022-05-17 19:25 UTC, thesanderchat commented on src/main/java/com/example/demo/group/GroupController.java
> +    @Autowired
fixed

2022-05-17 19:25 UTC, thesanderchat commented on src/main/java/com/example/demo/group/GroupController.java
> +    private GroupDto getGroups(@PathVariable("groupId") Long groupId) {
fixed

2022-05-17 19:25 UTC, thesanderchat commented on src/main/java/com/example/demo/group/GroupController.java
> +    private List<GroupDto> getGroups() {
fixed

2022-05-17 19:26 UTC, thesanderchat commented on src/main/java/com/example/demo/student/Student.java
> +    @PrimaryKeyJoinColumn(name = "groups_id")
fixed

2022-05-17 19:26 UTC, thesanderchat commented on src/main/java/com/example/demo/student/Student.java
>      private Integer age;
fixed

2022-05-18 18:57 UTC, aquariusmaster requested changes

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupMapperTest.java
> +    void toGroup() {
fix name

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupMapperTest.java
> +}
ad empty line

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupServiceTest.java
> +    void getGroups() {
???

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupServiceTest.java
> +    void getGroupById() {
???

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupServiceTest.java
> +    void addNewGroup() {
add correct name **name_When_Then**

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/group/GroupServiceTest.java
> +    void deleteGroup() {
same

2022-05-18 18:57 UTC, aquariusmaster commented on src/test/java/com/example/demo/student/StudentControllerTest.java
> +    void getStudentById() throws Exception {
check tests method names everywhere

2022-05-19 19:09 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupController.java
> +
remove empty line

2022-05-19 19:11 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +        for (StudentDto student : students
```
for (StudentDto student : students) {
    studentList.add(student);
    student.setGroupId(this.getId());
} 
```

2022-05-19 19:14 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    public void addNewListOfStudentsToStudentList(List<StudentDto> students) {
you don't use it, you can remove it
write only if you use it

2022-05-19 19:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupService.java
> +                .map(groupMapper::toGroupDto).orElseThrow(() -> new IllegalStateException("group with id " + groupId + " does not exists"));
use next formating:
```
stream()
    .map()
    .orElse()
```

2022-05-19 19:17 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupService.java
> +    public GroupService(GroupRepository groupRepository, GroupMapper groupMapper, StudentRepository studentRepository) {
use lombok

2022-05-19 19:29 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/StudentMapper.java
> +        if (student.getGroup() == null) {
you can simplify it by using elvis operator here

2022-05-19 19:30 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/StudentService.java
> +    private final StudentRepository studentRepository;
lombok

2022-05-23 20:16 UTC, aquariusmaster requested changes

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/Group.java
> +    @NonNull
duplicate non null? Does it have some purpose?

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupRepository.java
> +    List<Group> findAllByOrderByIdAsc();
add line at top and line at bottom

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupService.java
> +
remove empty line

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/GroupDto.java
> +    public GroupDto(@NonNull String name, @NonNull LocalDate dateOfCreation, List<StudentDto> studentList) {
Usually, we don't use many constructors. It's better to use Builder

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/student/StudentMapper.java
> +        Long groupId;
combine in one line

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/Group.java
> +        ) {
fix formating

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/Group.java
> +        this.setStudentList(null);
you cannot do that way. Check out this video to understand why: https://www.youtube.com/watch?v=-EpP0Vo63FM

2022-05-23 20:16 UTC, aquariusmaster commented on src/main/java/com/example/demo/group/Group.java
> +            student.setGroup(null);
Cover this line by tests: <img width="538" alt="Screenshot 2022-05-23 at 23 15 04" src="https://user-images.githubusercontent.com/6018601/169898834-3d187c5e-f396-4f4c-a3ee-4c9dd4b256e1.png">

2022-06-16 19:28 UTC, merged